name = "BaytesCore"
uuid = "e5a8efeb-54cd-4583-bf9c-87b09970f7ba"
authors = ["Patrick Aschermayr <p.aschermayr@gmail.com>"]
version = "0.2.0"

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SimpleUnPack = "ce78b400-467f-4804-87d8-8f486da07d0a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
ArgCheck = "2"
DocStringExtensions = "0.8, 0.9"
LogExpFunctions = "0.3"
SimpleUnPack = "1"
julia = "^1.9"
Random = "1.9"
Statistics = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
